### ISSUE TITLE
can not find "m5op.h"

### ISSUE THREAD

**Issue by CATHUR** [melver/mc2lib#1]
hey,
when I was looking at the code,I found that you include “m5op.h”,but I can't find it.
how can I find it？

**Comment by melver** [comment]
It's part of the gem5 source tree: https://gem5.googlesource.com/public/gem5/+/644e8cdf5ee7fcfe14faf6404ca42c18282dfceb/util/m5/m5op.h

**Comment by CATHUR** [comment]
Sorry to bother you again, Could you tell me what version of gem5 is?Because I run the code according to your paper, the errors are as follows:







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "melver/mc2lib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月10日(星期五) 晚上9:13
***@***.***&gt;;
抄送:&nbsp;"Mr ***@***.******@***.***&gt;;
主题:&nbsp;Re: [melver/mc2lib] can not find "m5op.h" (#1)





 
It's part of the gem5 source tree: https://gem5.googlesource.com/public/gem5/+/644e8cdf5ee7fcfe14faf6404ca42c18282dfceb/util/m5/m5op.h
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
